apiVersion: v1
kind: Service
metadata:
  name: gitops-secrets-service
spec:
  type: LoadBalancer
  selector:
    app: gitops-secrets-app
  ports:
     # - nodePort: 31400
      - protocol: TCP
        port: 8080
