apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-active
spec:
  type: LoadBalancer
  selector:
    app: trivial-go-web-app
  ports:
      #- nodePort: 31000
      - protocol: TCP
        port: 8080
